name: acronym
version: 1.0.0.2

dependencies:
  - base
  - split 

library:
  exposed-modules: Acronym
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
